options:
  volume-backend-name:
    type: string
    default:
    description: |
      Volume backend name for the backend. The default value is the
      application name in the Juju model.
  use-multipath:
    type: boolean
    default: True
    description: |
      Whether to use a multipath connection for iSCSI or FC in Cinder
      volume service. Enabling multipath for VMs is managed by the
      "use-multipath" option in the nova-compute charm.
  protocol:
    type: string
    default:
    description: |
      SAN protocol to use. Choose between iscsi or fc.
  san-ip:
    type: string
    default:
    description: |
      IP address of SAN controller.
  storwize-san-secondary-ip:
    type: string
    default:
    description: |
      Specifies secondary management IP or hostname to be used if san_ip
      is invalid or becomes inaccessible.
  san-login:
    type: string
    default:
    description: |
      Username for SAN controller.
  san-password:
    type: string
    default:
    description: |
      Password for SAN controller. SSH key pair authentication is not
      supported by the charm at this moment.
  storwize-svc-volpool-name:
    type: string
    default:
    description: |
      Comma separated list of storage system storage pools for volumes.
  storwize-preferred-host-site:
    type: string
    default:
    description: |
      Specifies the site information for host. One WWPN or multi-WWPNs
      used in the host can be specified. For example,
      "site1:wwpn1,site2:wwpn2&wwpn3" or "site1:iqn1,site2:iqn2"
  storwize-svc-mirror-pool:
    type: string
    default:
    description: |
      The name of the pool in which mirrored copy is stored.
  storwize-svc-stretched-cluster-partner:
    type: string
    default:
    description: |
      If operating in stretched cluster mode, specify the name of the
      pool in which mirrored copies are stored. e.g. "pool2"
  storwize-svc-vol-compression:
    type: boolean
    default:
    description: |
      Storage system compression option for volumes.
  storwize-svc-vol-iogrp:
    type: int
    default:
    description: |
      The I/O group in which to allocate volumes.
  storwize_svc_flashcopy_rate:
    type: int
    default:
    description: |
      Specifies the Storwize FlashCopy copy rate to be used when creating a full volume copy.
      The default is rate is 50, and the valid rates are 1-150.
